CREATE TABLE ClickLog(
	Id VARCHAR(32) PRIMARY KEY,
	LinkId VARCHAR(32),
	Metadata TEXT,
	CreatedAt DATETIME
);
CREATE TABLE Links(
	Id VARCHAR(32) PRIMARY KEY,
	Code VARCHAR(50) UNIQUE,
	Url VARCHAR(255),
	CreatedAt DATETIME
);
